"""Surface adapter protocol.

The artifact records intent (role+name, type, checkpoint). Adapters map that
intent onto a concrete substrate: Playwright today, accessibility/desktop later.
"""

from __future__ import annotations

from typing import Any, Protocol

from cuas.models.action import ActionSpec, Checkpoint, Locator, Target
from cuas.models.observation import Observation


class SurfaceAdapter(Protocol):
    async def goto(self, url: str) -> None: ...
    async def observe(self) -> Observation: ...
    async def resolve(self, target: Target) -> Any: ...
    async def execute(self, action: ActionSpec) -> dict[str, Any]: ...
    async def checkpoint(self, spec: Checkpoint) -> bool: ...
    async def screenshot(self, path: str) -> None: ...
    async def visible_text(self) -> str: ...
    async def current_url(self) -> str: ...
    async def title(self) -> str: ...
    async def extract_regex(self, pattern: str) -> str | None: ...
    async def close(self) -> None: ...
    def locator_debug(self, locator: Locator) -> str: ...
